---
- name: Play to deploy an operating system on a Raspberry
  hosts: builders
  tasks:
    - name: Run the main logic from the role
      block:
        - name: Call the role instructing it to execute the main logic
          vars:
            instruction: mainlogic
            requested_url: "{{ fedora_url }}"
            requested_checksum_url: "{{ fedora_image_checksum }}"
          include_role:
            name: fedora2sd
      rescue:
        - name: "RESCUE: Clean up the source Fedora LVM loopback devices"
          become: true
          shell: "lvchange -a n fedoraarm ; kpartx -d /dev/loop0 ; losetup -d /dev/loop0"

   
