---
- name: make sure local mount stubs exist
  become: true
  file:
    name: "{{ mountstub }}"
    mode: '0700'
    state: directory
- debug:
    msg: "Mounting {{ image }} on {{ mountstub }}"
- debug:
    var: partition
- name: "Mount lvm root partition in {{ mountstub }}"
  become: true
  mount:
    src: "{{ image }}"
    path: "{{ mountstub }}"
    opts: "rw,loop,offset={{ partition.begin | int }}"
    fstype: "{{ partition.fstype | regex_replace('fat32', 'vfat') }}"
    state: mounted
    fstab: /tmp/fstab.dummy
...
