---
- name: create a .ssh directory
  become: yes
  file:
    name: "{{ location }}/root/.ssh"
    mode: '0700'
    state: directory
  when: pubkey is defined

- name: create a file
  become: yes
  file:
    path: "{{ location }}/root/.ssh/authorized_keys"
    mode: '0600'
    state: touch
  when: pubkey is defined

- name: Set appropriate permissions on the authorized_keys file
  become: yes
  lineinfile:
    path: "{{ location }}/root/.ssh/authorized_keys"
    line: "{{ pubkey }}"
    state: present
  when: pubkey is defined

- name: Set root password
  become: yes
  lineinfile:
    path: "{{ location }}/etc/shadow"
    state: present
    line: 'root:{{ rootpasswordhash }}::0:99999:7:::'
    regexp: '^root:'
  when: rootpasswordhash is defined

- name: Set hostname
  become: yes
  copy:
    dest: "{{ location }}/etc/hostname"
    content: |
      {{ pi_hostname }}
  when: pi_hostname is defined

- name: Permit root login via ssh
  become: yes
  lineinfile:
    path: "{{ location }}/etc/ssh/sshd_config"
    state: present
    line: "PermitRootLogin yes"
    regexp: '^PermitRootLogin'

- name: Remove boot and boot/efi lines in fstab
  become: yes
  lineinfile:
    path: "{{ location }}/etc/fstab"
    state: absent
    regexp: '^.* /boot.*'

- name: Add boot to fstab
  become: yes
  lineinfile:
    path: "{{ location }}/etc/fstab"
    state: present
    line: "/dev/mmcblk0p1 /boot vfat defaults,noatime 0 0"
    regexp: '^.* / .*'

- name: Replace root line in fstab
  become: yes
  lineinfile:
    path: "{{ location }}/etc/fstab"
    state: present
    line: "/dev/mmcblk0p2 /     ext4 defaults,noatime 0 0"
    regexp: '^.* / .*'

- name: Copy over raspbian kernel modules
  become: yes
  command: "cp -uvrfp {{ raspbian_location }}/lib/modules {{ location }}/usr/lib"

- name: Copy over firmware
  become: yes
  command: "cp -uvrfp {{ raspbian_location }}/lib/firmware {{ location }}/lib"

- name: Copy over raspbian modprobe.d blacklist
  become: yes
  command: 'cp -uvrfp {{ raspbian_location }}/etc/modprobe.d/. {{ location }}/etc/modprobe.d/'

- name: "Deploy the {{ network.device }} network static interface configuration"
  become: yes
  template:
    src: templates/ifcfg.j2
    dest: "{{ location }}/etc/sysconfig/network-scripts/ifcfg-{{ network.device }}"
  when: network.bootproto != "dhcp"

- name: "Deploy the {{ network.device }} network dynamic interface configuration"
  become: yes
  template:
    src: templates/ifcfg-dhcp.j2
    dest: "{{ location }}/etc/sysconfig/network-scripts/ifcfg-{{ network.device }}"
  when: network.bootproto == "dhcp"

- name: Disable the initial-setup and other unneeded services
  become: yes
  file:
    path: "{{ location }}/etc/systemd/system/multi-user.target.wants/{{ item }}.service"
    state: absent
  loop:
    - initial-setup
    - abrtd
    - abrt-journal-core
    - abrt-oops
    - abrt-vmcore
    - abrt-xorg
    - cups
    - nfs-client
    - vboxservice
    - vmtoolsd
    - ModemManager
    - rngd
    - avahi-daemon
    - auditd
    - smartd
    - libvirtd
    - remote-fs
